import type { LabelSite } from './flowchart-labels'
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, expect, it, vi } from 'vitest'
import { Preview } from './preview'
import { editFlowchartLabel, inspectFlowchart, renderDiagram } from './renderer'

vi.mock('./renderer', () => ({ renderDiagram: vi.fn(), inspectFlowchart: vi.fn(), editFlowchartLabel: vi.fn() }))
beforeEach(() => {
  vi.stubGlobal('ResizeObserver', class { observe() {} disconnect() {} })
  Object.defineProperty(SVGElement.prototype, 'getBBox', { configurable: true, value: () => ({ x: 0, y: 0, width: 100, height: 100 }) })
  Object.defineProperty(SVGElement.prototype, 'viewBox', { configurable: true, value: { baseVal: { width: 100, height: 100 } } })
})
it('ignores stale async renders and reports recoverable syntax errors', async () => {
  let resolveOld: (svg: string) => void = () => {}
  vi.mocked(renderDiagram).mockImplementationOnce(() => new Promise((resolve) => {
    resolveOld = resolve
  })).mockResolvedValueOnce('<svg><text>Latest</text></svg>').mockRejectedValueOnce(new Error('Invalid syntax'))
  const onError = vi.fn()
  const { rerender } = render(<Preview source="old" title="Test diagram" onError={onError} />)
  await waitFor(() => expect(renderDiagram).toHaveBeenCalledTimes(1))
  rerender(<Preview source="latest" title="Test diagram" onError={onError} />)
  await waitFor(() => expect(screen.getByText('Live preview')).toBeVisible())
  await act(async () => resolveOld('<svg><text>Stale</text></svg>'))
  expect(screen.queryByText('Stale')).not.toBeInTheDocument()
  expect(screen.getByText('Latest')).toBeInTheDocument()
  rerender(<Preview source="broken" title="Test diagram" onError={onError} />)
  await waitFor(() => expect(screen.getByText('Unable to render')).toBeVisible())
  expect(screen.getByText('Latest')).toBeInTheDocument()
  expect(onError).toHaveBeenLastCalledWith('Invalid syntax')
  expect(screen.getByRole('button', { name: 'Zoom in' })).toBeEnabled()
  HTMLElement.prototype.scrollTo = vi.fn()
  fireEvent.click(screen.getByRole('button', { name: 'Zoom in' }))
  fireEvent.click(screen.getByRole('button', { name: 'Zoom out' }))
  fireEvent.click(screen.getByRole('button', { name: 'Fit' }))
  expect(HTMLElement.prototype.scrollTo).toHaveBeenCalled()
  expect(screen.getByRole('region', { name: 'Scrollable diagram canvas' })).toHaveAttribute('tabindex', '0')
})
it('zooms around the pointer with the wheel and pans by dragging', async () => {
  vi.mocked(renderDiagram).mockResolvedValue('<svg><text>Canvas</text></svg>')
  const width = vi.spyOn(Element.prototype, 'clientWidth', 'get').mockReturnValue(864)
  const height = vi.spyOn(Element.prototype, 'clientHeight', 'get').mockReturnValue(918)
  HTMLElement.prototype.setPointerCapture = vi.fn()
  render(<Preview source="flowchart TD" title="Canvas diagram" onError={vi.fn()} />)
  await waitFor(() => expect(screen.getByText('Live preview')).toBeVisible())
  const surface = screen.getByRole('region', { name: 'Scrollable diagram canvas' })
  const level = screen.getByLabelText('Zoom level')
  expect(level).toHaveTextContent('135%')
  expect(surface).toHaveAttribute('data-pan', 'ready')
  expect(surface).not.toHaveAttribute('data-editable')
  expect(screen.getByText('Drag to pan, scroll to zoom')).toBeVisible()

  const zoomed = 1.35 * Math.exp(0.24)
  expect(fireEvent.wheel(surface, { deltaY: -120, clientX: 100, clientY: 80 })).toBe(false)
  expect(level).toHaveTextContent('172%')
  expect(surface.scrollLeft).toBeCloseTo(32 + (68 / 1.35) * zoomed - 100)
  expect(surface.scrollTop).toBeCloseTo(32 + (48 / 1.35) * zoomed - 80)
  expect(fireEvent.wheel(surface, { deltaX: 40 })).toBe(true)
  expect(level).toHaveTextContent('172%')

  const left = surface.scrollLeft
  const top = surface.scrollTop
  fireEvent.pointerDown(surface, { button: 0, pointerId: 7, pointerType: 'mouse', clientX: 300, clientY: 200 })
  fireEvent.pointerMove(surface, { pointerId: 7, clientX: 302, clientY: 201 })
  expect(surface).toHaveAttribute('data-pan', 'ready')
  expect(HTMLElement.prototype.setPointerCapture).not.toHaveBeenCalled()
  fireEvent.pointerMove(surface, { pointerId: 7, clientX: 260, clientY: 150 })
  expect(surface).toHaveAttribute('data-pan', 'active')
  expect(HTMLElement.prototype.setPointerCapture).toHaveBeenCalledWith(7)
  expect(surface.scrollLeft).toBeCloseTo(left + 40)
  expect(surface.scrollTop).toBeCloseTo(top + 50)
  fireEvent.pointerUp(surface, { pointerId: 7 })
  expect(surface).toHaveAttribute('data-pan', 'ready')
  fireEvent.pointerDown(surface, { button: 0, pointerId: 8, pointerType: 'touch', clientX: 300, clientY: 200 })
  fireEvent.pointerMove(surface, { pointerId: 8, clientX: 200, clientY: 100 })
  expect(surface).toHaveAttribute('data-pan', 'ready')
  width.mockRestore()
  height.mockRestore()
})
it('selects and edits flowchart node labels on the diagram', async () => {
  const source = 'flowchart LR\nA["Old<br/>label"] --> B["`**md**`"]'
  const site: LabelSite = { nodeId: 'A', text: 'Old<br/>label', start: 16, end: 29, editable: true, form: 'quoted', replaceStart: 16, replaceEnd: 29 }
  const edited = 'flowchart LR\nA["New<br/>label"] --> B["`**md**`"]'
  vi.mocked(renderDiagram).mockResolvedValue('<svg><g class="node" id="diagram-4-flowchart-A-0"><text>Old label</text></g><g class="node" id="diagram-4-flowchart-B-1"><text>Bold</text></g></svg>')
  vi.mocked(inspectFlowchart).mockResolvedValue(new Map([['flowchart-A-0', site], ['flowchart-B-1', { ...site, nodeId: 'B', text: '`**md**`', editable: false, form: 'unsupported' }]]))
  vi.mocked(editFlowchartLabel).mockRejectedValueOnce(new Error('Labels edited on the diagram cannot contain double quotes or backticks.')).mockResolvedValueOnce(edited)
  HTMLElement.prototype.setPointerCapture = vi.fn()
  vi.spyOn(Element.prototype, 'clientWidth', 'get').mockReturnValue(864)
  vi.spyOn(Element.prototype, 'clientHeight', 'get').mockReturnValue(918)
  const onSourceChange = vi.fn()
  const onLocate = vi.fn()
  const { rerender } = render(<Preview source={source} title="Labels" onError={vi.fn()} onSourceChange={onSourceChange} onLocate={onLocate} />)
  const surface = screen.getByRole('region', { name: 'Scrollable diagram canvas' })
  await waitFor(() => expect(surface).toHaveAttribute('data-editable', 'ready'))
  expect(inspectFlowchart).toHaveBeenCalledWith(source, expect.any(Function))
  expect(screen.getByText(', double-click a node to edit')).toBeInTheDocument()

  const node = screen.getByText('Old label')
  fireEvent.click(node, { detail: 1 })
  expect(onLocate).toHaveBeenCalledWith({ start: 16, end: 29 })
  fireEvent.pointerDown(node, { button: 0, pointerId: 3, pointerType: 'mouse', clientX: 100, clientY: 100 })
  fireEvent.pointerMove(surface, { pointerId: 3, clientX: 140, clientY: 100 })
  expect(surface).toHaveAttribute('data-pan', 'active')
  fireEvent.pointerUp(surface, { pointerId: 3 })
  fireEvent.click(node, { detail: 1 })
  fireEvent.click(node, { detail: 2 })
  expect(onLocate).toHaveBeenCalledTimes(1)

  fireEvent.doubleClick(screen.getByText('Bold'))
  expect(screen.getByText('This label can only be edited in the source.')).toBeVisible()
  expect(screen.queryByRole('textbox', { name: 'Node label' })).not.toBeInTheDocument()

  fireEvent.doubleClick(node)
  const label = screen.getByRole('textbox', { name: 'Node label' })
  expect(label).toHaveValue('Old\nlabel')
  await waitFor(() => expect(label).toHaveFocus())
  expect(screen.queryByText('This label can only be edited in the source.')).not.toBeInTheDocument()
  fireEvent.change(label, { target: { value: 'Say "hi"' } })
  fireEvent.keyDown(label, { key: 'Enter' })
  expect(await screen.findByRole('alert')).toHaveTextContent('double quotes')
  expect(editFlowchartLabel).toHaveBeenLastCalledWith(source, 'A', 'Say "hi"')
  expect(label).toHaveAttribute('aria-invalid', 'true')
  fireEvent.change(label, { target: { value: 'New\nlabel' } })
  expect(screen.queryByRole('alert')).not.toBeInTheDocument()
  fireEvent.keyDown(label, { key: 'Enter' })
  await waitFor(() => expect(onSourceChange).toHaveBeenCalledWith(edited))
  expect(screen.queryByRole('textbox', { name: 'Node label' })).not.toBeInTheDocument()

  fireEvent.doubleClick(node)
  const discarded = screen.getByRole('textbox', { name: 'Node label' })
  await waitFor(() => expect(discarded).toHaveFocus())
  fireEvent.change(discarded, { target: { value: 'Discarded' } })
  fireEvent.keyDown(discarded, { key: 'Escape' })
  expect(screen.queryByRole('textbox', { name: 'Node label' })).not.toBeInTheDocument()
  fireEvent.doubleClick(node)
  fireEvent.blur(screen.getByRole('textbox', { name: 'Node label' }))
  expect(screen.queryByRole('textbox', { name: 'Node label' })).not.toBeInTheDocument()
  expect(editFlowchartLabel).toHaveBeenCalledTimes(2)
  expect(onSourceChange).toHaveBeenCalledTimes(1)

  rerender(<Preview source={'sequenceDiagram\nA->>B: Hi'} title="Labels" onError={vi.fn()} onSourceChange={onSourceChange} onLocate={onLocate} />)
  await waitFor(() => expect(screen.getByText('Live preview')).toBeVisible())
  expect(surface).not.toHaveAttribute('data-editable')
  fireEvent.doubleClick(screen.getByText('Old label'))
  expect(screen.getByText('Only flowchart node labels can be edited on the diagram.')).toBeVisible()
})

it('only activates node targets after the matching source settles', async () => {
  const source = '---\ntitle: Overview\n---\nflowchart LR\nA[One]\nclick A "one.mmd"'
  const svg = '<svg><g class="node" id="diagram-1-flowchart-A-0"><text>One</text></g></svg>'
  let finish: (svg: string) => void = () => {}
  vi.mocked(renderDiagram).mockResolvedValueOnce(svg).mockImplementationOnce(() => new Promise((resolve) => {
    finish = resolve
  })).mockRejectedValueOnce(new Error('Invalid syntax'))
  const onOpenFile = vi.fn()
  const onError = vi.fn()
  const { rerender } = render(<Preview source={source} title="Index" onError={onError} onOpenFile={onOpenFile} />)
  await waitFor(() => expect(screen.getByText('Live preview')).toBeVisible())
  const link = screen.getByText('One').closest('g')!
  expect(link).toHaveAttribute('aria-label', 'Open one.mmd')
  fireEvent.click(screen.getByText('One'))
  expect(onOpenFile).toHaveBeenLastCalledWith('one.mmd')

  rerender(<Preview source={source.replace('one.mmd', 'two.mmd')} title="Index" onError={onError} onOpenFile={onOpenFile} />)
  expect(link).not.toHaveAttribute('data-file-link')
  expect(link).not.toHaveAttribute('tabindex')
  fireEvent.click(link)
  fireEvent.keyDown(link, { key: 'Enter' })
  expect(onOpenFile).toHaveBeenCalledTimes(1)
  await waitFor(() => expect(renderDiagram).toHaveBeenCalledTimes(2))
  await act(async () => finish(svg))
  expect(link).toHaveAttribute('data-file-link', 'two.mmd')
  fireEvent.keyDown(link, { key: ' ' })
  expect(onOpenFile).toHaveBeenLastCalledWith('two.mmd')

  rerender(<Preview source={`${source}\nclick A "../outside.mmd"`} title="Index" onError={onError} onOpenFile={onOpenFile} />)
  await waitFor(() => expect(screen.getByText('Unable to render')).toBeVisible())
  expect(link).not.toHaveAttribute('data-file-link')
  fireEvent.click(link)
  expect(onOpenFile).toHaveBeenCalledTimes(2)
})
