import assert from 'node:assert/strict'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { resolve } from 'node:path'

async function main() {
  const root = resolve(import.meta.dirname, '../..')
  const scratch = resolve(root, 'tmp/directory-design')
  await mkdir(scratch, { recursive: true })
  const target = process.env.MERDECK_DIRECTORY_DESIGN_URL
  assert.ok(target, 'MERDECK_DIRECTORY_DESIGN_URL must identify the HTTP prototype')
  const origin = new URL(target)
  assert.equal(origin.protocol, 'http:')
  assert.ok(origin.hostname.endsWith('.localhost'))
  const html = await readFile(resolve(import.meta.dirname, 'Directory-navigation.html'), 'utf8')
  const envelope = html.replace(/<script>[\s\S]*<\/script>/, '<script></script>')
  assert.ok(!/\b(?:src|href)\s*=\s*["'](?!data:|#)/i.test(envelope))
  assert.ok(!/@import\s/.test(envelope))
  const metadata = JSON.parse(await readFile(resolve(import.meta.dirname, '_d_meta.json'), 'utf8'))
  assert.equal(metadata.assets['Directory navigation'].versions[0].status, 'needs-review')
  assert.equal(metadata.assets.Merdeck.versions[0].status, 'needs-review')
  assert.equal(metadata.assets['Brand mark sheet'].versions[0].status, 'approved')
  const fromWeb = createRequire(resolve(root, 'web/package.json'))
  const { chromium, expect } = await import(fromWeb.resolve('@playwright/test')) as typeof import('@playwright/test')
  const browser = await chromium.launch({ headless: true })
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, colorScheme: 'light', reducedMotion: 'reduce' })
  const errors: string[] = []
  const requests: string[] = []
  const checks: string[] = []
  await context.route('**/*', (route) => {
    if (route.request().url() === target)
      return route.continue()
    requests.push(route.request().url())
    return route.abort()
  })
  const page = await context.newPage()
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error')
      errors.push(message.text())
  })
  const button = (name: string) => page.getByRole('button', { name, exact: true })
  const row = (name: string) => page.locator('.directory-list').getByRole('button', { name: new RegExp(`^${name.replaceAll('.', '\\.')}($| Unopened)`) })
  const shot = (name: string) => page.screenshot({ path: resolve(scratch, `${name}.png`), fullPage: true, animations: 'disabled' })
  try {
    const response = await page.goto(target)
    assert.equal(response?.status(), 200)
    await expect(page.locator('.diagram-graphic svg')).toBeVisible()
    const editor = page.getByRole('textbox', { name: 'Mermaid source' })
    const source = await editor.inputValue()
    const changed = `${source}\n%% retained draft\n`
    await editor.fill(changed)
    await row('docs').click()
    await row('platform').click()
    await expect(page.getByRole('heading', { name: 'overview.mmd', exact: true })).toBeVisible()
    await expect(editor).toHaveValue(changed)
    await button('docs').click()
    await expect(row('guide.md')).toBeVisible()
    await button('Up').click()
    await expect(button('Up')).toBeDisabled()
    checks.push('Folder, ancestor, Up and Root preserve selected path and dirty source')
    await page.getByRole('textbox', { name: 'Filter loaded files' }).fill('no-match')
    await page.getByRole('tab', { name: 'Markdown', exact: true }).click()
    await expect(row('docs')).toBeVisible()
    await expect(row('archive')).toBeVisible()
    await expect(row('overview.mmd')).toHaveCount(0)
    await row('archive').click()
    for (let index = 0; index < 5; index++) await button('Next page').click()
    await expect(page.getByText('Pages 2–6 · 15 loaded files', { exact: true })).toBeVisible()
    await expect(page.getByText('Earlier pages are no longer shown. Restart to see them.')).toBeVisible()
    await expect(page.getByText('No matching files in the loaded window.', { exact: false })).toBeVisible()
    await expect(editor).toHaveValue(changed)
    await page.getByRole('tab', { name: 'All', exact: true }).click()
    await expect(row('diagram-01.mmd')).toHaveCount(0)
    await expect(row('diagram-18.mmd')).toBeVisible()
    await shot('desktop-window')
    await button('Restart').click()
    await expect(row('diagram-01.mmd')).toBeVisible()
    await expect(page.getByText('Pages 1–1 · 3 loaded files', { exact: true })).toBeVisible()
    checks.push('Five-page window, eviction, honest filters and explicit restart')
    await button('Root').click()
    await row('empty').click()
    await expect(page.getByText('No supported entries in this directory.', { exact: false })).toBeVisible()
    await expect(button('Next page')).toBeDisabled()
    await expect(editor).toHaveValue(changed)
    checks.push('Empty directory keeps the draft and does not assert filesystem emptiness')
    await button('Root').click()
    for (const state of ['loading', 'error', 'stale', 'depth']) {
      await button('Prototype states').click()
      await button(state).click()
      await expect(editor).toHaveValue(changed)
      await expect(button('Next page')).toBeDisabled()
      await shot(`state-${state}`)
    }
    await button('Restart').click()
    await row('docs').click()
    await row('guide.md').click()
    await expect(page.getByRole('heading', { name: 'Reading document…' })).toBeVisible()
    await expect(button('Diagram 2')).toBeVisible()
    await button('Diagram 2').click()
    await expect(editor).toHaveValue(/sequenceDiagram/)
    await row('notes.md').click()
    await expect(page.getByRole('heading', { name: 'No Mermaid blocks' })).toBeVisible()
    await row('unreadable.md').click()
    await expect(page.getByRole('heading', { name: 'Document unavailable' })).toBeVisible()
    await button('overview.mmd').click()
    await expect(editor).toHaveValue(changed)
    checks.push('Deferred Markdown loading, block selection, zero/error states and retained drafts')
    await page.getByRole('button', { name: 'Dark theme', exact: true }).click()
    await expect(page.locator('html')).toHaveClass('dark')
    await expect(page.getByText('Live preview', { exact: true })).toBeVisible()
    await shot('desktop-dark')
    await page.getByRole('button', { name: 'Light theme', exact: true }).click()
    await expect(page.locator('html')).not.toHaveClass('dark')
    await expect(page.getByText('Live preview', { exact: true })).toBeVisible()
    await shot('desktop-light')
    await page.getByRole('button', { name: 'System theme', exact: true }).click()
    await page.emulateMedia({ colorScheme: 'dark' })
    await expect(page.locator('html')).toHaveClass('dark')
    await page.emulateMedia({ colorScheme: 'light' })
    await expect(page.locator('html')).not.toHaveClass('dark')
    checks.push('Light, dark and system preferences reuse the application theme')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('tab', { name: 'Source', exact: true }).click()
    await expect(editor).toHaveValue(changed)
    await shot('narrow-source')
    const open = button('Open project files')
    await open.click()
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    await shot('narrow-drawer')
    const bounds = await dialog.boundingBox()
    assert.ok(bounds && bounds.x >= 0 && bounds.x + bounds.width <= 390)
    for (let index = 0; index < 20; index++) {
      await page.keyboard.press('Tab')
      await expect.poll(() => dialog.evaluate(node => node.contains(document.activeElement)), { message: 'Focus escaped drawer' }).toBe(true)
    }
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(open).toBeFocused()
    await open.press('Enter')
    await dialog.getByRole('button', { name: 'docs', exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(dialog.getByRole('button', { name: 'platform', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('tab', { name: 'Preview', exact: true }).click()
    await expect(page.locator('.diagram-graphic svg')).toBeVisible()
    await expect(page.getByText('Live preview', { exact: true })).toBeVisible()
    await button('Fit').click()
    await expect.poll(() => page.locator('.diagram-graphic svg').evaluate((svg) => {
      const frame = svg.getBoundingClientRect()
      return [...svg.querySelectorAll('g.node')].every((node) => {
        const bounds = node.getBoundingClientRect()
        return bounds.left >= frame.left - 1 && bounds.right <= frame.right + 1 && bounds.top >= frame.top - 1 && bounds.bottom <= frame.bottom + 1
      })
    }), { message: 'Every fitted node remains inside the narrow SVG' }).toBe(true)
    await shot('narrow-preview')
    const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
    assert.equal(horizontalOverflow, false)
    checks.push('390px drawer, keyboard activation, focus trap/restore, source/preview and no horizontal overflow')
    await page.keyboard.press('Control+s')
    await expect(button('Save')).toBeDisabled()
    assert.deepEqual(errors, [])
    assert.deepEqual(requests, [])
    checks.push('Fixture save shortcut; no browser errors or external requests; self-contained HTML')
    await writeFile(resolve(scratch, 'check-results.json'), `${JSON.stringify({ target, checks, errors, requests, viewports: ['1440x960', '390x844'] }, null, 2)}\n`)
    process.stdout.write(`PASS ${checks.length} directory prototype groups at ${target}\n`)
  }
  finally {
    await writeFile(resolve(scratch, 'browser-diagnostics.json'), `${JSON.stringify({ errors, requests, checks }, null, 2)}\n`)
    await browser.close()
  }
}
main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
