import type { DiagramDocument } from '../../../../src/shared/contracts'
import { describe, expect, it } from 'vitest'
import { dirty, draftsReducer, warningMessage } from './drafts'

export function document(version = 'a', first = 'A', second = 'B'): DiagramDocument {
  return { path: 'docs/example.md', kind: 'markdown', version: version.repeat(64), blocks: [first, second].map((source, index) => ({ source, label: `Diagram ${index + 1}`, selector: { kind: 'markdown', id: `md:${index}:${version === 'a' ? 10 : 20}:${30 + index}` }, lineStart: index + 1, lineEnd: index + 2 })) }
}
const path = 'docs/example.md'
const load = () => draftsReducer({}, { type: 'load', document: document() })
describe('scoped draft reconciliation', () => {
  it('refreshes clean files but keeps dirty edits on stale loads and navigation', () => {
    let state = load()
    state = draftsReducer(state, { type: 'load', document: document('b', 'new') })
    expect(state[path]?.sources[0]).toBe('new')
    state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'draft' })
    state = draftsReducer(state, { type: 'load', document: document('c', 'external') })
    expect(state[path]?.sources[0]).toBe('draft')
    expect(dirty(state[path]!)).toBe(true)
    expect(draftsReducer(state, { type: 'edit', path: 'other.mmd', block: 0, source: 'x' })).toBe(state)
  })
  it('keeps edits during saves and refreshes sibling selectors without losing their drafts', () => {
    let state = load()
    state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'submitted' })
    state = draftsReducer(state, { type: 'edit', path, block: 1, source: 'sibling draft' })
    state = draftsReducer(state, { type: 'saving', path, id: 1, block: 0 })
    state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'newer typing' })
    state = draftsReducer(state, { type: 'saved', path, id: 1, document: document('b', 'submitted') })
    expect(state[path]?.sources).toEqual(['newer typing', 'sibling draft'])
    expect(state[path]?.baseline.blocks[1]?.selector).toEqual(document('b').blocks[1]?.selector)
    expect(state[path]?.baseline.version).toBe('b'.repeat(64))
    expect(dirty(state[path]!)).toBe(true)
  })
  it('uses canonical saved text and ignores old save responses', () => {
    let state = load()
    state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'submitted' })
    state = draftsReducer(state, { type: 'saving', path, id: 2, block: 0 })
    expect(draftsReducer(state, { type: 'saved', path, id: 1, document: document('c') })).toBe(state)
    state = draftsReducer(state, { type: 'saved', path, id: 2, document: document('b', 'submitted\n') })
    expect(dirty(state[path]!)).toBe(false)
  })
  it('never rebases external changes, deletion, conflicts or ambiguous sibling changes', () => {
    let state = load()
    state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'draft' })
    state = draftsReducer(state, { type: 'revision', revision: { path, state: 'present', version: 'c'.repeat(64) } })
    expect(warningMessage(state[path]?.warning)).toContain('outside')
    expect(state[path]?.baseline.version).toBe('a'.repeat(64))
    state = draftsReducer(state, { type: 'revision', revision: { path, state: 'deleted' } })
    expect(warningMessage(state[path]?.warning)).toContain('deleted')
    expect(draftsReducer(state, { type: 'saving', path, id: 1, block: 0 })).toBe(state)
    state = draftsReducer(state, { type: 'reload', document: document() })
    state = draftsReducer(state, { type: 'saving', path, id: 2, block: 0 })
    state = draftsReducer(state, { type: 'saved', path, id: 2, document: document('b', 'A', 'different sibling') })
    expect(warningMessage(state[path]?.warning)).toContain('different document layout')
    expect(state[path]?.baseline.version).toBe('a'.repeat(64))
  })
  it('retains unsaved work on expiry and requires explicit discard after reauthentication', () => {
    let state = load()
    state = draftsReducer(state, { type: 'edit', path, block: 1, source: 'recoverable' })
    state = draftsReducer(state, { type: 'expire' })
    expect(state[path]?.locked).toBe(true)
    expect(state[path]?.sources[1]).toBe('recoverable')
    expect(draftsReducer(state, { type: 'load', document: document('b') })).toBe(state)
    state = draftsReducer(state, { type: 'reload', document: document('b') })
    expect(state[path]?.locked).toBe(false)
    expect(draftsReducer(state, { type: 'clear' })).toEqual({})
    expect(draftsReducer(load(), { type: 'expire' })).toEqual({})
  })
  it('preserves drafts when a save fails and ignores stale errors', () => {
    let state = load()
    state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'keep' })
    state = draftsReducer(state, { type: 'saving', path, block: 0, id: 5 })
    expect(draftsReducer(state, { type: 'error', path, id: 4, message: 'old' })).toBe(state)
    state = draftsReducer(state, { type: 'error', path, id: 5, message: 'Conflict' })
    expect(state[path]?.sources[0]).toBe('keep')
    expect(state[path]?.saving).toBeNull()
  })
})
it('allows explicit recovery only against the unchanged full-file revision', () => {
  let state = load()
  state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'retained' })
  state = draftsReducer(state, { type: 'expire' })
  expect(draftsReducer(state, { type: 'retain', document: document('b') })).toBe(state)
  state = draftsReducer(state, { type: 'retain', document: document() })
  expect(state[path]?.locked).toBe(false)
  expect(state[path]?.sources[0]).toBe('retained')
  expect(state[path]?.warning).toBeNull()
})

it.each(['revision', 'load'] as const)('clears only a matching own-save observation from %s', (type) => {
  let state = load()
  state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'submitted' })
  state = draftsReducer(state, { type: 'edit', path, block: 1, source: 'sibling draft' })
  state = draftsReducer(state, { type: 'saving', path, block: 0, id: 1 })
  state = draftsReducer(state, type === 'load' ? { type, document: document('b', 'submitted') } : { type, revision: { path, state: 'present', version: 'b'.repeat(64) } })
  state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'newer' })
  state = draftsReducer(state, { type: 'saved', path, id: 1, document: document('b', 'submitted') })
  expect(state[path]?.warning).toBeNull()
  expect(state[path]?.sources).toEqual(['newer', 'sibling draft'])
  state = draftsReducer(state, { type: 'saving', path, block: 1, id: 2 })
  expect(state[path]?.saving?.version).toBe('b'.repeat(64))
})
it.each(['external', 'deleted', 'session', 'layout', 'mutation'] as const)('never clears %s evidence when an own-save response arrives later', (kind) => {
  let state = load()
  state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'submitted' })
  state = draftsReducer(state, { type: 'saving', path, block: 0, id: 1 })
  state = draftsReducer(state, { type: 'revision', revision: { path, state: 'present', version: 'b'.repeat(64) } })
  state = draftsReducer(state, { type: 'load', document: document('b', 'submitted') })
  state = draftsReducer(state, { type: 'edit', path, block: 0, source: 'newer' })
  if (kind === 'external') {
    state = draftsReducer(state, { type: 'revision', revision: { path, state: 'present', version: 'c'.repeat(64) } })
    state = draftsReducer(state, { type: 'load', document: document('c', 'external') })
  }
  if (kind === 'deleted')
    state = draftsReducer(state, { type: 'revision', revision: { path, state: 'deleted' } })
  if (kind === 'session')
    state = draftsReducer(state, { type: 'expire' })
  if (kind === 'mutation')
    state = draftsReducer(state, { type: 'error', path, id: 1, message: 'Conflict' })
  state = draftsReducer(state, { type: 'saved', path, id: 1, document: document('b', 'submitted', kind === 'layout' ? 'changed sibling' : 'B') })
  state = draftsReducer(state, { type: 'load', document: document('b', 'submitted') })
  state = draftsReducer(state, { type: 'revision', revision: { path, state: 'present', version: 'b'.repeat(64) } })
  expect(state[path]?.warning).not.toBeNull()
  expect(state[path]?.sources[0]).toBe('newer')
  expect(draftsReducer(state, { type: 'saving', path, block: 0, id: 2 })).toBe(state)
})
